//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_KHACHSAN
    {
        public string MaKS { get; set; }
        public string TenKS { get; set; }
        public Nullable<System.DateTime> NgayNhanPhong { get; set; }
        public Nullable<System.DateTime> NgayTraPhong { get; set; }
        public Nullable<int> SoHanhKhach { get; set; }
        public Nullable<int> SoPhong { get; set; }
        public Nullable<int> tongtien { get; set; }
    }
}
