//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_CHUYENBAY
    {
        public string MaVe { get; set; }
        public string DiemKhoiHanh { get; set; }
        public string DiemDen { get; set; }
        public Nullable<int> SoHanhKhach { get; set; }
        public Nullable<System.DateTime> NgayDi { get; set; }
        public Nullable<System.DateTime> Ngayve { get; set; }
        public string HangGhe { get; set; }
        public Nullable<int> tongtien { get; set; }
    
        public virtual VE_MAY_BAY VE_MAY_BAY { get; set; }
    }
}
