//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATTOUR
    {
        public string MAVET { get; set; }
        public string TENT { get; set; }
        public Nullable<int> TIENT { get; set; }
        public string MaKH { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
