//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON
    {
        public string MaHD { get; set; }
        public string MaKH { get; set; }
        public Nullable<int> SoLuongVe { get; set; }
        public string Loaive { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
