//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACH_HANG
    {
        public KHACH_HANG()
        {
            this.DATTOURs = new HashSet<DATTOUR>();
            this.DUA_DOAN_SAN_BAY = new HashSet<DUA_DOAN_SAN_BAY>();
            this.HOA_DON = new HashSet<HOA_DON>();
            this.KHACH_SAN = new HashSet<KHACH_SAN>();
            this.VE_MAY_BAY = new HashSet<VE_MAY_BAY>();
        }
    
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string DiaChi { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> SDT { get; set; }
    
        public virtual ICollection<DATTOUR> DATTOURs { get; set; }
        public virtual ICollection<DUA_DOAN_SAN_BAY> DUA_DOAN_SAN_BAY { get; set; }
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        public virtual ICollection<KHACH_SAN> KHACH_SAN { get; set; }
        public virtual ICollection<VE_MAY_BAY> VE_MAY_BAY { get; set; }
    }
}
