//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_BAY
    {
        public SAN_BAY()
        {
            this.DUA_DOAN_SAN_BAY = new HashSet<DUA_DOAN_SAN_BAY>();
        }
    
        public string MaSB { get; set; }
        public string TenSB { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> SDT { get; set; }
    
        public virtual ICollection<DUA_DOAN_SAN_BAY> DUA_DOAN_SAN_BAY { get; set; }
    }
}
