//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eshop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TOUR_DULICHEntities2 : DbContext
    {
        public TOUR_DULICHEntities2()
            : base("name=TOUR_DULICHEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMIN> ADMINs { get; set; }
        public DbSet<CHITIET_CHUYENBAY> CHITIET_CHUYENBAY { get; set; }
        public DbSet<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        public DbSet<CHITIET_KHACHSAN> CHITIET_KHACHSAN { get; set; }
        public DbSet<DATTOUR> DATTOURs { get; set; }
        public DbSet<DUA_DOAN_SAN_BAY> DUA_DOAN_SAN_BAY { get; set; }
        public DbSet<HOA_DON> HOA_DON { get; set; }
        public DbSet<JRPASS> JRPASSes { get; set; }
        public DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public DbSet<KHACH_SAN> KHACH_SAN { get; set; }
        public DbSet<K> KS { get; set; }
        public DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public DbSet<SAN_BAY> SAN_BAY { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public DbSet<THUE_XE> THUE_XE { get; set; }
        public DbSet<TOUR> TOURs { get; set; }
        public DbSet<VE_MAY_BAY> VE_MAY_BAY { get; set; }
    }
}
